some enhancements and cleanups

diff --git a/scripts/.local/bin/swaycmds/menu_do b/scripts/.local/bin/swaycmds/menu_do
--- a/scripts/.local/bin/swaycmds/menu_do
+++ b/scripts/.local/bin/swaycmds/menu_do
@@ -9,23 +9,21 @@
 set -e
 
 config_dir="$HOME/.config"
-menu_cmd="bemenu"
+menu_cmd() { bemenu -l 20 --fn 'Droid Sans Mono-9' -p "${prompt}" -w -i ;}
+paster() { wl-paste ;}
+
 
 script_name=$(basename $0)
 config_name=$(echo $script_name | tr -dc '[:alnum:]_')
-prompt=${config_name^}
+prompt="${config_name} >"
 
-[ ! -f "$config_dir/$config_name" ] && \
-    echo "Missing config: $config_name" && exit 1
+[ ! -f "${config_file:=$config_dir/$config_name}" ] && \
+    echo "Missing config: $config_file" && exit 1
 
-choice=$(
-    grep -v "#" "$config_dir/$config_name" | sort | \
-        sed -r 's/"\<([^"]+)"/\1/g' | \
-        awk -F: '{ st = index($0,":");printf "%s\t→\t%s\n", $1, substr($0,st+1)}' | \
-    ${menu_cmd} -l 10 --fn 'Droid Sans Mono-9' -p "$prompt> " 
-)
+export clip=$(paster)
 
-if [ $? = "0" ] ; then
-   echo $choice |
-       sh -c "$(awk  -F'→'  '{ print $2 }')"&
-fi
+grep -v "#" "$config_file" | sort | \
+    sed -r 's/"\<([^"]+)"/\1/g' | \
+    awk -F':' '{ st = index($0,":");printf "%s\t→\t%s\n", $1, substr($0,st+1)}' | \
+    (menu_cmd || exit1) | \
+    setsid -f sh -c "$(awk  -F'→'  '{ print $2 }')"
